### ISSUE TITLE
[JIRA Server] Order of User Stories

### ISSUE THREAD

**Issue by stritti** [Sybit-Education/Diveni#196]
Order of user stories within Diveni session is different to order within JIRA Server.

https://github.com/Sybit-Education/Diveni/blob/963d0ee33fc5635e79410d717f056ae51e3b0113/backend/src/main/java/io/diveni/backend/service/projectmanagementproviders/jiraserver/JiraServerService.java#L155

**Comment by KzuDemEvin** [comment]
It seemed to be an issue with the ordering of issues by RANK. In our JIRA _(German)_ we have to use RANG instead of RANK. But it is configurable in the .env file.
[Example in .env:](https://github.com/Sybit-Education/Diveni/blob/main/backend/.env.example#L26)
`JIRA_SERVER_RANKNAME=RANG`

I am closing this issue for now.
