### ISSUE TITLE
Fontend: filter JIRA projects

### ISSUE THREAD

**Issue by stritti** [Sybit-Education/Diveni#224]
**Is your feature request related to a problem? Please describe.**

If the list of projects on JIRA is very long, it is difficult to find correct project.

**Describe the solution you'd like**

Probably we could add a Autocomplete-Input, which filters on typing project name:

![image](https://user-images.githubusercontent.com/184547/195860279-03e3ad65-1b51-41e9-91db-536c1ced9d05.png)

**Comment by SponsoredByPuma** [comment]
@stritti Do you want a seperate search bar, which shows the user his input ?
I'm asking this, because you can already filter for a certain project.
For example if you want to look for the Project "Diveni", you need to click on the project selection Component and just start typing the name of the project. In this case "Diveni". The component will jump to the "Diveni" Project and already select it for you. But you can also just type in the first letter of the project and the component will jump to all the project which start with the typed-in letter. The only downside of this is, that you need to be fast while typing in your project or else it will recognize each input as a seperate input ( = starting letter).

**Comment by stritti** [comment]
@SponsoredByPuma I think filtering would be nice if you do not remember initial letter it is more comfortable to type part of name.

**Comment by SponsoredByPuma** [comment]
already done
