### ISSUE TITLE
Diveni Stat

### ISSUE THREAD

**Issue by SponsoredByPuma** [Sybit-Education/Diveni#484]
**Describe the bug**
Whenever we restart the backend all of our Diveni Data is gone.

**Expected behavior**
The Diveni Date should not be deleted when we restart our backend.

**Comment by stritti** [comment]
I think it could be an issue of Docker environment. The database should be persisted outside the container.

**Comment by Dan1elBox** [comment]
I just tested it, and from what I've seen, our database persists the data even across restarts.
The issue, I believe, lies in how we are trying to persist our old/deleted sessions for the Overall/Last Month Statistics.

We calculate the Overall Sessions as follows in our [AnalyticsController](https://github.com/Sybit-Education/Diveni/blob/main/backend/src/main/java/io/diveni/backend/controller/AnalyticsController.java): 
`int amountOfAllSessions = databaseService.getSessions().size() + databaseService.getDeletedSessions().size();`
So, we retrieve all the currently active sessions from the database along with all the deleted sessions(from the DatabaseService).


If we take a closer look, we are trying to store the old/deleted sessions for statistics calculation in **line 27** of the [DatabaseService](https://github.com/Sybit-Education/Diveni/blob/main/backend/src/main/java/io/diveni/backend/service/DatabaseService.java): `private List<Session> deletedSessions = new ArrayList<>();`.

However, this is a design flaw as this list does not persist throughout the runtime of the backend application and gets reset after every restart. This means that after every container restart of the backend, the list of deletedSessions in the DatabaseService is empty, resulting in only the currently active sessions being displayed after each restart.

**Comment by stritti** [comment]
Okay, this was a misunderstanding from my side. Sorry, @Dan1elBox

**Comment by Dan1elBox** [comment]
I believe we have two options to solve this problem:

1. We could either permanently store the old sessions in the database, which means we would stop deleting them automatically. We can modify the SessionsScheduledTasks to avoid automatically deleting old sessions after 2 days and, instead, only set a status flag to mark the session as "old/deleted." We would also need to adapt the closeSession method to follow the same behavior.
**However, this approach would result in our database quickly becoming cluttered with old sessions.**

2. Alternatively, we could simply create a new table named "statistics" in our database, which would include the attributes "OverallSessions" and "OverallAttendees." We would increment the "OverallSessions" and "OverallAttendees" attributes automatically each time someone creates a new session or a member joins a session. We would still retrieve the current statistics from our session table for our "currently statistics/view."
**This method would prevent the database from getting filled with old sessions, but it would lead to more frequent database accesses. Additionally, based on my initial observation, we wouldn't be able to display the "Last Month statistics/view" since we would no longer have access to the sessions and the creationTime/lastModified attributes.**

What do you think of the options? Do you have other ideas? 😃 @stritti @SponsoredByPuma

**Comment by stritti** [comment]
Another approach could be to add another service as docker container and log data there.
Some services like Google Analytics: https://opensource.com/article/18/1/top-5-open-source-analytics-tools
